name: CI - build front

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  ag-prueba-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
            node-version: '18'

      - name: Install dependencies
        working-directory: ag-prueba-front
        run: npm install

      - name: Build Angular app
        working-directory: ag-prueba-front
        run: npm run build
